name: A workflow for my Hello World file
on: push

env:
  NAME_PARAMETER: ${{ secrets.MY_NAME }}
  
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "${{ env.NAME_PARAMETER }}"
